### ISSUE TITLE
Retrospective Meeting - 2nd meeting 

### ISSUE THREAD

**Issue by SujoodEldouma** [MIT-Emerging-Talent/2024-group-01-collaboration-practice#7]
Meeting time: Monday 12:45 EST (After The “Big Picture” of Data Science" session)

Agenda: 

- [x] We need to update/complete the following files:
  - constraints
  - communication
  - READme
- [x] Retrospective ( Milestone 0)
  - How to plan project work/ task division 
  - group norms
  - How's everyone with Git/GitHub
  - study plan?
- [ ] CDSP problem identification ( Milestone 1)
  - which domain do we want to work in?
  - brainstorming for project ideas

**Comment by SujoodEldouma** [comment]
Thank you all for attending.

Meeting Minutes: 

- We worked through the agenda and updated the documents that required team discussions.
  - communication.md requires further individual editing (ASAP).
  - our communication plan is to have weekly stable meetings (time around 11:00 EST); we will agree on the date based on the above file
  - Small meetings are TBD on a need basis.
 
- Plan for Milestone 1: (deadline for it is 26th):
   - This stage is a diverging stage: brainstorm and come up with as many great ideas and questions as we want to work on
       - We will create an issue on Github to share/discuss these ideas (waiting on Evan to assign the new repo)
       - Let's focus on creating ideas at this stage more than debating them or assessing their solvability. 
       - 2-3 days for this stage
   - The following stage is a converging stage: we assess everything the group came up with and agree on the problem identification and scope of work. 
   - The deliverables for this milestone are on the 29th.

**Comment by Lourdes148** [comment]
Hello Everybody,
I Hope you' re very fine. I see on slack an Evan' s proposition about our group. I would know our decision.
Sincerely,

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., janv. 22, 2024 à 15:16, ***@***.***> a écrit:   


Thank you all for attending.

Meeting Minutes:
   
   -    
We worked through the agenda and updated the documents that required team discussions.
      
      - communication.md requires further individual editing (ASAP).
      - our communication plan is to have weekly stable meetings (time around 11:00 EST); we will agree on the date based on the above file
      - Small meetings are TBD on a need basis.

   -    
Plan for Milestone 1: (deadline for it is 26th):
      
      - This stage is a diverging stage: brainstorm and come up with as many great ideas and questions as we want to work on         
         - We will create an issue on Github to share/discuss these ideas (waiting on Evan to assign the new repo)
         - Let's focus on creating ideas at this stage more than debating them or assessing their solvability.
         - 2-3 days for this stage

      - The following stage is a converging stage: we assess everything the group came up with and agree on the problem identification and scope of work.
      - The deliverables for this milestone are on the 29th.
